AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false